### PR TITLE
Added opinions.. and Webpack.

### PR DESCRIPTION
**Pull request by colshacol**
For the most part, I added Webpack. It builds to be about 0.3 KiB more than the rollup bundle, and it is just one single UMD module, rather than 3 different modules.

I haven't tested to see if the module works! Maybe you can give `jits` a shot and take it to CodeSandbox to test!

Anywho, I also changed the code a bit. Not all of the changes were opinionated. Most were to see how it affected the bundle size. -- If it made the bundle size smaller, I left the change there. (Like destructuring.)

Unnecessary changes:

1. Prettier.
2. Prettier on commit.
3. EditorConfig.

To run my Webpack config, clone my fork, `yarn`, and then `yarn webpack`.

I can give more detail later when I am not late to work. ;)

### CODE REVIEW

**Comment by alexvcasillas** [comment]
Hey @colshacol sorry for keeping you on hold with this, I've been a little busy with work.

I've been checking your PR and I have to say a few things, I like how you structured the `cratebox-react` `Provider` and `Consumer`, I'll keep it that way because it improves the overall bundle size 👏 

On the other hand, I've been checking the webpack thing and I have to say I'm a little surprised. Check this out:

image

It's like 0.53KB more just by changing from Rollup to Webpack. I'm not sure about this, we should discuss this further :)

**Comment by colshacol** [comment]
Let's leave it open for a bit. I feel like I have been challenged to bring the size down to be close to that of Rollup. ;)

Don't take the code changes just yet, either. They are somewhat dependent on the custom babel I used. (i.e `if (...) throw new Error()` will break without a specific babel plugin.)

**Comment by alexvcasillas** [comment]
Ok, friend! I'll wait for this :)

**Comment by colshacol** [comment]
Oh yeah, and also -- when considering that extra .53KB of bundle size, don't forget that the one UMD bundle created by Webpack works for all 3 of the bundles spit out by Rollup.

> These are modules which are capable of working everywhere, be it in the client, on the server or elsewhere. The UMD pattern typically attempts to offer compatibility with the most popular script loaders of the day (e.g RequireJS amongst others). In many cases it uses AMD as a base, with special-casing added to handle CommonJS compatibility.

**Comment by alexvcasillas** [comment]
But with Rollup and the package.json configured I can tell at the install moment what bundle to use. Or that's how it's supossed to work 🤔

**Pull request closed without merging**
